config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, skip: :all
  devise_scope :admin_user do
    get 'admin/login' => 'devise/sessions#new', as: :new_admin_user_session
    post 'login' => 'devise/sessions#create', as: :admin_user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_admin_user_session
  end
  resources :events, only: %i[index show new create destroy] do
    resources :event_offers, only: %i[new create show update]
  end

  resources :posts
  resources :questions, only: %i[show new create update]

  resource :admin_user, only: %i[show]



  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :events, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  # 複数で使うので共通化
  scope :not_sent, -> { where(admin_checked: false)}
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin_user
  has_many :event_offers,  dependent: :destroy
  validates :date, presence: true
end

app/models/event_offer.rb
class EventOffer < ApplicationRecord
  belongs_to :event
  validates :name, presence: true
  # TODO
  # メアドのバリデーション実装
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin_user
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :authenticate_admin_user!
  def show
    # Todo:あとで絞り込み実装(全て、未対応(対応済み))
    @event_offers     = EventOffer.not_sent
    @all_event_offers = EventOffer.all

    @questions        = Question.not_sent
    @all_questions    = Question.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    admin_user_path
  end
end

app/controllers/event_offers_controller.rb
class EventOffersController < ApplicationController
  before_action :set_event
  before_action :authenticate_admin_user!, only: %i[show update]

  def new
    @event_offer = @event.event_offers.build
  end

  def create
    @event_offer = @event.event_offers.build(params_event_offer)
    if @event_offer.save
      flash[:notice] = "ご応募ありがとうございます。\n管理者からメールが届きますのでお待ちください。"
      redirect_to events_path
    else
      render 'event_offers/new'
    end
  end

  # ここは管理者のみ
  def show
    @event_offer = EventOffer.find(params[:id])
  end

  # ここは管理者のみ
  def update
    EventOffer.find(params[:id]).update_attribute(:admin_checked, true)
    flash[:notice] = "送信済みにしたヨ"
    redirect_to admin_user_path
  end

  private
    def set_event
      @event = Event.find(params[:event_id])
    end

    def params_event_offer
      params.require(:event_offer).permit(:name, :email, :remark, :event_id)
    end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_admin_user!, only: %i[new create destroy]
  before_action :set_event, only: %i[show destroy]

  def index
    @events = Event.all.order(date: "DESC")
  end

  def show
    @event_offer = @event.event_offers.build
  end

  def new
    @event = current_admin_user.events.build
  end

  def create
    @event = current_admin_user.events.create(params_events)
    flash[:notice] = "イベントを作成したヨ"
    redirect_to events_path
  end

  def destroy
    @event.destroy
    flash[:notice] = "イベント削除したヨ"
    redirect_to events_path
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def params_events
      params.require(:event).permit(:title, :content, :place, :date)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin_user!, only: %i[new create destroy edit update]
  before_action :set_post, only: %i[show destroy edit update]

  def index
    @posts = Post.all.order(id: "DESC")
  end

  def show; end

   # ここから管理者のみ↓ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  def new
    @post = current_admin_user.posts.build
  end

  def create
    @post = current_admin_user.posts.create(params_posts)
    redirect_to @post
  end

  def edit; end

  def update
    if @post.update(params_posts)
      flash[:notice] = "日記を編集したヨ"
      redirect_to posts_path
    else
      render edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "日記削除したヨ"
    redirect_to posts_path
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def params_posts
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_admin_user!, only: %i[show update]

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      flash[:notice] = "お問い合わせありがとうございます。\n管理者からメールが届きますのでお待ちください。"
      redirect_to root_path
    else
      render 'new'
    end
  end

  # ここは管理者のみ
  def show
    @question = Question.find(params[:id])
  end

  # ここは管理者のみ
  def update
    Question.find(params[:id]).update_attribute(:admin_checked, true)
    flash[:notice] = "対応済みにしたヨ"
    redirect_to current_admin_user
  end


  private
  def params_question
    params.require(:question).permit(:name, :email, :title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = " ")
    base_title = "就活分析"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/event_offers_helper.rb
module EventOffersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin_users/show.html.erb
<%  provide(:title, "管理者ページ") %>
<h1>管理者ページ</h1>
<h3>作成系</h3>
<%= link_to "日記作成", new_post_path, class: "btn btn-primary" %> |
<%= link_to "イベント作成", new_event_path, class: "btn btn-primary" %>
<hr>

<!--イベント系-->
<h3><%= @event_offers.present? ? "未読イベント申し込み一覧" : "" %></h3>
<ul>
  <% @event_offers.each do |e| %>
    <li><%= e.created_at %>：<%= link_to e.event.title, event_event_offer_path(e.event, e) %></li>
  <% end %>
</ul>
<hr>

<h3>全イベント申し込み一覧</h3>
<ul>
  <% @all_event_offers.each do |e| %>
    <li><%= e.created_at %>：<%= link_to e.event.title, event_event_offer_path(e.event, e) %></li>
  <% end %>
</ul>
<hr>

<!--お問い合わせ-->
<h3><%= @questions.present? ? "未対応イベント一覧" : "" %></h3>
<ul>
  <% @questions.each do |q| %>
    <li><%= q.created_at %>：<%= link_to q.name, q %>さん</li>
  <% end %>
</ul>
<hr>

<h3>お問い合わせ一覧</h3>
<ul>
  <% @all_questions.each do |q| %>
    <li><%= q.created_at %>：<%= link_to q.name, q %>さん</li>
  <% end %>
</ul>
<hr>

<%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete, class: "btn btn-danger" %>

app/views/event_offers/new.html.erb
<%  provide(:title, "イベント申し込み") %>
<h1>〜応募概要〜</h1>
<h2 class="text-left">タイトル：<%= @event.title %></h2>
<h4 class="text-left">日付：<%= @event.date %> スタート</h4>
<h4 class="text-left">場所：<%= @event.place %></h4>
<br>

<h1>〜応募フォーム〜</h1>
<%= form_for @event_offer, url: event_event_offers_url do |f| %>
  <%= render "shared/error_messages", object: @event_offer %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control my-form", placeholder: "お名前を入力" %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control my-form", placeholder: "メールアドレスを入力" %>
  <br>

  <%= f.label :remark %>
  <%= f.text_area :remark, class: "form-control my-form", size: "30x8", placeholder: "内容を入力" %>
  <br>

  <%= f.hidden_field :event_id, value: @event.id %>

  <%= f.submit "応募する", class: "btn btn-success" %>
<% end %>
<br><br><br>

app/views/event_offers/show.html.erb
<%  provide(:title, "イベント申し込み詳細") %>
<h1>応募確認ページ</h1>
<p>名前：<%= @event_offer.name %></p>
<p>メールアドレス：<%= @event_offer.email %></p>
<p>備考：<%= simple_format(@event_offer.remark? ? @event_offer.remark : "なし") %></p>
<br>
<h4>イベント詳細</h4>
<p>イベント名；<%= @event.title %></p>
<p>スタート時間：<%= @event.date %></p>
<p>場所：<%= @event.place %></p>
<br>
<% if @event_offer.admin_checked? %>
  <p class="btn btn-info">※送信済み</p>
<% else %>
  <%= form_for @event_offer, url: event_event_offer_url(@event) do |f|   %>
    <%= f.submit "メール送信済みにする", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/events/index.html.erb
<%  provide(:title, "イベント一覧") %>
<h1 class="text-center">イベント一覧</h1>
<div class="">
  <table class="">
    <thead>
    <tr>
      <th>日時</th>
      <th>イベント名</th>
      <th>場所</th>
      <% if admin_user_signed_in? %>
        <th>管理者項目</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @events.each do |e| %>
      <tr>
        <td><%= e.date %></td>
        <td><%= link_to e.title, e %></td>
        <td><%= e.place %></td>
        <% if admin_user_signed_in? %>
          <td><%= link_to "削除", e, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>
<br>

app/views/events/new.html.erb
<%  provide(:title, "イベント作成") %>
<h1>イベント作成ページ</h1>
<hr>
<%= form_for @event do |f| %>
  <!--  ないと思うけど...-->
  <%= render "shared/error_messages", object: @event %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control my-form", placeholder: "タイトルを入力" %>
  <br>

  <%= f.label :date %> <br>
  <%= f.datetime_select :date, class: "form-control my-form",minute_step: 10 %>
  <br><br>

  <%= f.label :place %>
  <%= f.text_field :place, class: "form-control my-form", placeholder: "場所を入力" %>
  <br>

  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control my-form", size: "30x8", placeholder: "内容を入力" %>
  <br>

  <%= f.submit "作成する", class: "btn btn-success" %>
<% end %>

app/views/events/show.html.erb
<%  provide(:title, "イベント詳細") %>
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <h1 class="text-left"><%= @event.title %></h1>
    <h3 class="text-left d-inline-block pull-left">日付：<%= @event.date %> スタート</h3>
    <h3 class="text-left d-inline-block pull-right">場所：<%= @event.place %></h3>
    <br><br>
    <h2 class="text-left">〜内容〜</h2>
    <p><%= simple_format(@event.content) %></p>
    <br>

    <p><%= link_to "応募フォームへ進む", new_event_event_offer_path(@event), class: "btn btn-primary" %></p>
    <p><%= link_to "戻る", events_path, class: "btn btn-info" %></p>
  </div>
  <div class="col-sm-2"></div>
</div>
<br><br><br>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- 端末のサイズに応じて画面を描写 -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

</head>

app/views/layouts/_header.html.erb
<!--<header class="navbar navbar-fixed-top navbar-inverse">-->
<!--  <div class="container">-->
    <%#= link_to "就活分析", root_path, id: "logo" %>
<!--    <nav>-->
<!--      <ul class="nav navbar-nav navbar-right navbar-expand-sm navbar-dark bg-dark mt-3 mb-3">-->
<!--        <li class="pc-menu"><%#= link_to "Home", root_path, class: "navbar-brand" %></li>-->
<!--        <li class="pc-menu"><%#= link_to "就活振り返り日記", posts_path %></li>-->
<!--        <li class="pc-menu"><%#= link_to "イベント一覧", events_path %></li>-->
<!--        <li class="pc-menu"><%#= link_to "お問い合わせ", new_question_path %></li>-->
<!--        <li class="dropdown phone-menu">-->
<!--          <a href="#" class="dropdown-toggle" data-toggle="dropdown">メニュー<span class="caret"></span></a>-->
<!--          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">-->
<!--            <li><%#= link_to "Home", root_path %></li>-->
<!--            <li><%#= link_to "就活振り返り日記", posts_path, class: "dropdown-item" %></li>-->
<!--            <li><%#= link_to "イベント一覧", events_path, class: "nav-link" %></li>-->
<!--            <li><%#= link_to "お問い合わせ", new_question_path, class: "nav-link" %></li>-->
<!--          </ul>-->
<!--        </li>-->

<!--      </ul>-->
<!--    </nav>-->
<!--  </div>-->
<!--</header>-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to "就活分析", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "就活振り返り日記", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "イベント一覧", events_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "お問い合わせ", new_question_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>
<body>
<%= render 'layouts/header' %>

<div class="row main-page">
  <div class="col-md-1 color-grey"></div>
  <div class="col-md-10 main-page">
    <% if notice %>
      <h3 class="alert alert-success"><%= simple_format(notice) %></h3>
    <% elsif alert %>
      <h3 class="alert alert-danger"><%= simple_format(alert) %></h3>
    <% end %>
    <%= yield %>
  </div>
  <div class="col-md-1 color-grey"></div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<br>
<%= form_for @post do |f| %>
  <!--  ないと思うけど...-->
  <%= render "shared/error_messages", object: @post %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control my-form", placeholder: "タイトルを入力" %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control my-form", size: "30x8", placeholder: "内容を入力" %>
  <br>
  <%= f.submit "送信する", class: "btn btn-success" %>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "日記編集") %>
<h1>日記編集ページ</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<%  provide(:title, "日記一覧") %>
<h1 class="text-center">就活振り返り日記</h1>
<div class="text-center">
  <table class="text-center">
    <thead>
    <tr>
      <th>投稿日</th>
      <th>タイトル</th>
      <th>更新日時</th>
      <% if admin_user_signed_in? %>
        <th>管理者項目</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @posts.each do |p| %>
      <tr>
        <td><%= p.created_at.strftime("%Y年%m月%d日") %></td>
        <td><%= link_to p.title, p %></td>
        <td><%= p.created_at.strftime("%H:%M") %></td>
        <% if admin_user_signed_in? %>
          <td> <%= link_to "編集", edit_post_path(p) %> |
            <%= link_to "削除", p, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>
<br>

app/views/posts/new.html.erb
<%  provide(:title, "日記作成") %>
<h1>日記作成ページ</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<%  provide(:title, "日記詳細") %>
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <h1 class="text-center"><%= @post.title %></h1>
    <p class="text-right"><%= @post.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
    <br>
    <h4><%= simple_format(@post.content) %></h4>
    <br><br><br>

    <% begin %>
      <% Post.find(params[:id].to_i - 1) %>
      <%= link_to "<< 前へ", post_path(Post.find(params[:id].to_i - 1)), class: "d-inline-block btn btn-primary pull-left" %>
    <% rescue %>
    <% end %>

    <% begin %>
      <% Post.find(params[:id].to_i + 1) %>
      <%= link_to "次へ >>", post_path(Post.find(params[:id].to_i + 1)), class: "d-inline-block btn btn-primary pull-right" %>
    <% rescue %>
    <% end %>

  </div>
  <div class="col-sm-2"></div>
</div>

app/views/questions/new.html.erb
<%  provide(:title, "お問い合わせ") %>
<h1>お問い合わせフォーム</h1>
<%= form_for @question do |f| %>
  <%= render "shared/error_messages", object: @question %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control my-form", placeholder: "お名前を入力" %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control my-form", placeholder: "メールアドレスを入力" %>
  <br>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control my-form", placeholder: "件名を入力" %>
  <br>

  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control my-form", size: "30x8", placeholder: "内容を入力" %>
  <br>

  <%= f.submit "送信する", class: "btn btn-success" %>
<% end %>
<br><br><br>

app/views/questions/show.html.erb
<%  provide(:title, "お問い合わせ詳細") %>
<h1>お問い合わせ確認ページ</h1>
<p>名前：<%= @question.name %></p>
<p>メールアドレス：<%= @question.email %></p>
<p>件名：<%= @question.title.presence || "なし" %></p>
<p>内容：<%= simple_format(@question.content) %></p>
<br>
<br>
<% if @question.admin_checked? %>
  <p class="btn btn-info">※対応済み</p>
<% else %>
  <%= form_for @question do |f|   %>
    <%= f.submit "対応済みにする", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= object.errors.count %>個エラーがあります
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li class="red"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/welcome/index.html.erb
<div class="text-center">
  <h1 class="main-logo">他人に任せる自己分析</h1>
  <h1 class="main-logo-pc">他人に任せる<br>自己分析</h1>
  <%= image_tag "main_logo.jpg", class: "text-center" %>
</div>